export const reducerCases = {
    SET_TOKEN :"SET_TOKEN",
    SET_PLAYLIST:"SET_PLAYLISTS",
    SET_USER:"SET_USER",
    SET_PLAYLIST:"SET_PLAYLIST",
    SET_PLAYLIST_ID:"SET_PLAYLIST_ID",
    SET_CURRENT_TRACK:"SET_CURRENT_TRACK",
    SET_PLAYER_STATE:"SET_PLAYER_STATE",
}